server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: ghassan
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
  main:
    web-application-type: servlet # use "none" for disable the tomcat server